version: '3'
services:
  app:
    image: mcr.microsoft.com/devcontainers/javascript-node:20
    volumes:
      - .:/workspace:cached
    command: sleep infinity
  db:
    image: postgres:16
    environment:
      POSTGRES_PASSWORD: MerchantEmpires2025$
      POSTGRES_DB: game_db
    ports:
      - "5432:5432"
